### ISSUE TITLE
lvscare checks whether multiple ports are feasible

### ISSUE THREAD

**Issue by kubecto** [labring/lvscare#41]
lvscare checks whether multiple ports are feasible

```
spec:
  containers:
  - args:
    - care
    - --vs
    - 10.249.249.249:6443
    - 10.249.249.249:10002
    - --health-path
    - /healthz
    - --health-schem
    - https
    - --rs
    - 10.102.26.35:6443
    - 10.202.26.35:10002
    - --rs
    - 10.102.26.36:6443
    - 10.102.26.36:10002
    - --rs
    - 10.102.26.37:6443
    - 10.102.26.37:10002
```
